def image

pipeline {
    agent any
    stages {
        stage('Build') {                 
            steps {
                script {
                     sh '''pwd '''
                    sh '''ls -l '''
                    sh '''ls -l ./m4'''
                     //image = docker.build("1156/jdemos:apache", "--pull -f m4/Dockerfile1 m4")
                    image = docker.build("1156/jdemos:apache", " -f .m4/Dockerfile1 m4")
                   
                }                
            }
        }   
        stage('Smoke Test') {
            steps {
                script {
                    container = image.run()
                    container.stop()
              }
            }
        }
        stage('Push') {                 
            steps { 
                script {
                    withDockerRegistry([credentialsId: "dockerhub", url: "" ]) {        
                        image.push()
                    }     
                }
            }
        }
    }
}
