library identifier: 'jenkins-pipeline-demo-library@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/anoopmohan3/jenkins-pipeline-demo-library.git'])

//crossPlatformBuild repoName: 'sixeyed/pi-psod-pipelines',
crossPlatformBuild repoName: '1156/jdemos',
                     linuxContext: 'm4', 
                      windowsContext: 'm4'
